name: Run Python Script

on:
  schedule:
    - cron: "0 14 * * 1-5"  # 14:00 UTC = 11:00 AM Argentina (UTC-3)
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install

      - name: Run Python script
        run: python main.py
